THEME_NAME = "webcafe.exe pastel vintage internet"

BACKGROUND_BLUE = "#A8D8EA"
BACKGROUND_LILAC = "#C9C4F4"

WINDOW_BODY = "#F7F4F8"
WINDOW_FRAME = "#EADDE6"
TITLE_BAR_PINK = "#F3A6C8"

BORDER_LAVENDER = "#A8A1F0"
OUTLINE_PURPLE = "#8C86D8"
TEXT_PURPLE = "#8E88E6"

SOFT_WHITE = "#FFFDFE"
ACCENT_PINK = "#F6B6D1"